//General Variables
export const ERRORS = "ERRORS"
export const CLEAR_MESSAGES = "CLEAR_MESSAGES"
export const SUCCESS_MESSAGES = "SUCCESS_MESSAGES"
export const SUCCESS = "SUCCESS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const SET_lOADING = "SET_lOADING"
export const SET_FORM_lOADING = "SET_FORM_lOADING"
export const SET_LOGED_IN = "SET_LOGED_IN"
export const SET_SINGLE_TO_NULL = "SET_SINGLE_TO_NULL"


//sorting
export const SORT_PRODUCTS = "SORT_PRODUCTS"
export const FILTER_ITEMS = "FILTER_ITEMS"
export const FILTER_PRODUCTS = "FILTER_PRODUCTS"
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH"
export const SORT_PRICE = "SORT_PRICE"
export const SET_FILTERED_TO_NULL = "SET_FILTERED_TO_NULL"


//destination variables
export const ADD_DESTINATION = "ADD_DESTINATION"
export const GET_DESTINATIONS = "GET_DESTINATIONS"
export const GET_DESTINATION = "GET_DESTINATION"
export const DELETE_DESTINATION = "DELETE_DESTINATION"
export const UPDATE_DESTINATION = "UPDATE_DESTINATION"
export const SET_CURRENT_DESTINATION = "SET_CURRENT_DESTINATION"

//User variable
export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const SET_LOGIN = "SET_LOGIN"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const UPDATE_USER = "UPDATE_USER"
export const GET_USER = "GET_USER"


//Carts
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const INCREASE_CART_ITEM_QTY = "INCREASE_CART_ITEM_QTY"
export const DECREASE_CART_ITEM_QTY = "DEREASE_CART_ITEM_QTY"
export const CLEAR_CART = "CLEAR_CART"
export const SET_COUPON_VALUE = "SET_COUPON_VALUE"
export const SET_SHIPPING_CHARGE = "SET_SHIPPING_CHARGE"
export const GET_CART_ITEMS = "GET_CART_ITEMS"
export const GET_CART_TOTALS = "GET_CART_TOTALS"
export const GET_CART_COUPON_WORTH = "GET_CART_COUPON_WORTH"


//Wish List
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"


//categories
export const GET_CLOTHINGS = "GET_CLOTHINGS"
export const GET_SHOES = "GET_SHOES"
export const GET_ELECTRONICS = "GET_ELECTRONICS"
export const GET_RELATED_PRODUCTS = "GET_RELATED_PRODUCTS"


// website settings
export const NAVBAR_TOGGLE = "NAVBAR_TOGGLE"
export const CLOSE_NAVBAR = "CLOSE_NAVBAR"


//Product Variables
export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCT = "GET_PRODUCT"
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"
export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS"
export const GET_BRANDS = "GET_BRANDS"


//Category Variables
export const ADD_CATEGORY = "ADD_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_CATEGORY = "GET_CATEGORY"


//reviews variables
export const SUBMIT_REVIEW = "SUBMIT_REVIEW"
export const GET_REVIEWS = "GET_REVIEWS"
export const GET_REVIEW = "GET_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"


//orders variables
export const ADD_TO_ORDERS = "ADD_TO_ORDERS"
export const GET_ORDERS = "GET_ORDERS"
export const GET_ORDER = "GET_ORDER"


//admin variables with actions
export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const GET_CUSTOMER = "GET_CUSTOMER"
export const GET_SALES = "GET_SALES"
export const GET_DAILY_SALES = "GET_DAILYSALES"
export const GET_WEEKLY_SALES = "GET_WEEKLY_SALES"
export const GET_MONTHLY_SALES = "GET_MONTHLY_SALES"
export const GET_TRANSACTIONS = "GET_TRANSACTIONS"
export const GET_TRANSACTION = "GET_TRANSACTION"
export const SET_CUSTOMER_TO_NULL = "SET_CUSTOMER_TO_NULL"





